name: qr_school_attendance
description: QR based school attendance app
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2
  csv: ^6.0.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
